name: Docker Image CI

on:
  pull_request:
    types:
      - closed

jobs:
  push_to_registry:
    if: github.event.pull_request.merged == true
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: fordataws/aws-sdk-code-examples
      
      - name: Build and push Docker image - Ruby
        if: contains(github.event.pull_request.labels.*.name, 'lang/ruby')
        uses: docker/build-push-action@master
        with:
          context: ruby
          push: true
          tags: fordataws/ruby:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image - Rust
        if: contains(github.event.pull_request.labels.*.name, 'lang/rust')
        uses: docker/build-push-action@master
        with:
          context: rust_dev_preview
          push: true
          tags: fordataws/rust:latest
          labels: ${{ steps.meta.outputs.labels }}
