name: Rust
on:
  push:
    paths:
      - "rust_dev_preview/**"
    branches:
      - main
  pull_request:
    paths:
      - "rust_dev_preview/**"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    name: "Rust: test clippy lint audit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cd rust_dev_preview
          cargo test --all-targets --all-features && \
          cargo clippy --all-targets && \
          cargo fmt -- --check && \
          cargo audit
